description: DigitalOcean cloud, k8s Kubernetes cluster with ArgoCD
options:
  - name: name
    description: Project name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,32}$"
    default: "demo-project"
  - name: organization
    description: Organization name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,64}$"
    default: "my-organization"
  - name: region
    description: DigitalOcean region
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,32}$"
    default: "ams3"
  - name: domain
    description: DigitalOcean DNS zone domain name
    regex: "^[a-zA-Z0-9][a-zA-Z0-9-\\.]{1,61}[a-zA-Z0-9]\\.[a-zA-Z]{2,}$"
    default: "cluster.dev"
  - name: bucket_name
    description: DigitalOcean spaces bucket name for states
    regex: "^[a-zA-Z][a-zA-Z0-9\\-]{0,64}$"
    default: "cdev-state"
help_message: | 
  ###############################################################################
  # Cluster.dev project generation for DigitalOcean cloud.                      #
  # cdev console tool generator                                                 #
  ###############################################################################
  Before your begin:                                           
  1) Export your DIGITALOCEAN_TOKEN. (https://www.digitalocean.com/docs/apis-clis/api/create-personal-access-token/)
  2) Export SPACES_ACCESS_KEY_ID and SPACES_SECRET_ACCESS_KEY. (https://www.digitalocean.com/community/tutorials/how-to-create-a-digitalocean-space-and-api-key)
  3) Create spaces bucket for Terraform states in the chosen region. (https://www.digitalocean.com/docs/spaces/quickstart/#create-a-space)
  4) Create domain in DigitalOcean domains service. (https://www.digitalocean.com/docs/networking/dns/how-to/add-domains/)
  5) Use cdev command to plan and apply project infrastructure.
