apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 4.4.3
    helm:
      values: |
        rbac:
          create: "true"
        provider: digitalocean
        digitalocean:
          apiToken: {{ reqEnv "DIGITALOCEAN_TOKEN" }}
        interval: "1m"
        policy: "sync"
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true